# CHON recalculation  label=s1 Mix_9 E=0.05 MeV  1.0 cm fixed  events=1e6
/control/verbose 1
/run/verbose 1
/random/setSeeds 1090507 1090508
/det/clearMaterial
/det/setMaterialName Mix_9
/det/setDensity 1.381458 g/cm3
/det/setThickness 1.0 cm
/det/addElement C 0.4883821311
/det/addElement H 0.0717119422
/det/addElement O 0.4031889948
/det/addElement N 0.0329507814
/det/addElement S 0.0037661506
/run/setCut 0.001 mm
/det/createMaterial
/scan/setEnergyGrid 0.05
/scan/setEvents 1000000
/run/initialize
