# CHON recalculation  label=s1 Mix_7 E=1.5 MeV  1.0 cm fixed  events=1e6
/control/verbose 1
/run/verbose 1
/random/setSeeds 1072207 1072208
/det/clearMaterial
/det/setMaterialName Mix_7
/det/setDensity 1.349681 g/cm3
/det/setThickness 1.0 cm
/det/addElement C 0.5056364013
/det/addElement H 0.0731871425
/det/addElement O 0.3477425921
/det/addElement N 0.0659015628
/det/addElement S 0.0075323012
/run/setCut 0.001 mm
/det/createMaterial
/scan/setEnergyGrid 1.5
/scan/setEvents 1000000
/run/initialize
