# CHON recalculation  label=s2 Mix_4 E=0.662 MeV  1.0 cm fixed  events=1e6
/control/verbose 1
/run/verbose 1
/random/setSeeds 2041707 2041708
/det/clearMaterial
/det/setMaterialName Mix_4
/det/setDensity 1.389034 g/cm3
/det/setThickness 1.0 cm
/det/addElement C 0.4983845972
/det/addElement H 0.0667781141
/det/addElement O 0.3200968761
/det/addElement N 0.1029711919
/det/addElement S 0.0117692206
/run/setCut 0.001 mm
/det/createMaterial
/scan/setEnergyGrid 0.662
/scan/setEvents 1000000
/run/initialize
