# CHON recalculation  label=s2 Mix_10 E=1.33 MeV  1.0 cm fixed  events=1e6
/control/verbose 1
/run/verbose 1
/random/setSeeds 2102107 2102108
/det/clearMaterial
/det/setMaterialName Mix_10
/det/setDensity 1.414767 g/cm3
/det/setThickness 1.0 cm
/det/addElement C 0.4711278608
/det/addElement H 0.0702367418
/det/addElement O 0.4586353974
/run/setCut 0.001 mm
/det/createMaterial
/scan/setEnergyGrid 1.33
/scan/setEvents 1000000
/run/initialize
