# CHON recalculation  label=s2 Mix_6 E=0.05 MeV  1.0 cm fixed  events=1e6
/control/verbose 1
/run/verbose 1
/random/setSeeds 2060507 2060508
/det/clearMaterial
/det/setMaterialName Mix_6
/det/setDensity 1.319334 g/cm3
/det/setThickness 1.0 cm
/det/addElement C 0.5228906716
/det/addElement H 0.0746623429
/det/addElement O 0.2922961895
/det/addElement N 0.0988523443
/det/addElement S 0.0112984518
/run/setCut 0.001 mm
/det/createMaterial
/scan/setEnergyGrid 0.05
/scan/setEvents 1000000
/run/initialize
