# CHON controlled exchange base E=0.03 MeV
/control/verbose 1
/run/verbose 1
/random/setSeeds 4000027 4000028
/det/clearMaterial
/det/setMaterialName base
/det/setDensity 1.352033 g/cm3
/det/setThickness 1.0 cm
/det/addElement C 0.5066366479
/det/addElement H 0.0726937597
/det/addElement N 0.0729036039
/det/addElement O 0.3394333802
/det/addElement S 0.0083326082
/run/setCut 0.001 mm
/det/createMaterial
/scan/setEnergyGrid 0.03
/scan/setEvents 1000000
/run/initialize
