# CHON controlled exchange dALL E=0.03 MeV
/control/verbose 1
/run/verbose 1
/random/setSeeds 4005027 4005028
/det/clearMaterial
/det/setMaterialName dALL
/det/setDensity 1.352033 g/cm3
/det/setThickness 1.0 cm
/det/addElement C 0.3766366479
/det/addElement H 0.0876937597
/det/addElement N 0.1229036039
/det/addElement O 0.3894333802
/det/addElement S 0.0233326082
/run/setCut 0.001 mm
/det/createMaterial
/scan/setEnergyGrid 0.03
/scan/setEvents 1000000
/run/initialize
